#!/bin/bash

function show_help() {
  echo "Shows time in UNIX Epoch format."
  echo "Usage:"
  printf '  %s [-m]\n' "$(basename "$0")"
  cat <<EOF
Options:
  -m, --milliseconds    Displays the time in milliseconds (optional).
  -h, --help            Shows this message.
EOF
}

if [[ "$*" == *" -h"* ]] || [[ "$*" == *" --help"* ]]; then
  show_help
  exit 0
fi

case $1 in
-h | --help)
  show_help
  exit 0
  ;;
-m | --milliseconds)
  if [[ $(which python3) ]]; then
    python3 -c 'import time; print(int(time.time() * 1000))'
    exit 0
  else
    printf "python3 is required to show time with millisecond precision.\n"
    exit 1
  fi
  ;;
"")
  date +%s
  exit $?
  ;;
*)
  printf "Unknown option: %s\n" "${1}"
  exit 1
  ;;
esac
