#!/bin/bash

function show_help() {
  echo "Shows time in UNIX Epoch format."
  echo "Usage:"
  printf '  %s [-m]\n' "$(basename "$0")"
  cat <<EOF
Where:
  -m, --milliseconds    Displays the time in milliseconds (optional).
  -h, --help            Shows this message.
EOF
}

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

milliseconds="false"

while :; do
  case $1 in
  -h | --help)
    show_help
    exit 0
    ;;
  -m | --milliseconds)
    milliseconds="true"
    shift
    ;;
  --)
    shift
    break
    ;;
  -?*)
    die "Unknown option: ${1}"
    ;;
  *)
    if [[ -n $1 ]]; then
      die "Unknown option: ${1}"
    else
      break
    fi
    ;;
  esac
done

if [[ $milliseconds == "true" ]]; then
  if [[ $(which python3) ]]; then
    python3 -c 'import time; print(int(time.time() * 1000))'
  else
    die 'python3 is required to show time with millisecond precision.'
  fi
else
  date +%s
fi

exit 0
