#!/bin/bash

function show_help() {
  echo "Generates a random number padded with zeroes (0)."
  echo "Usage:"
  printf '  %s [number]\n' "$(basename "$0")"
  cat <<EOF
Where:
  number      If specified, the script will generate a random integer between 0 and [number].
              If no number is specified, the upper limit defaults to 9999.
  -h, --help  Shows this message.
EOF
}

function randomize() {
  digits=$1
  regex='^[0-9]+$'
  if [[ $digits =~ $regex ]]; then
    printf '%0*d\n' "${#digits}" "$((RANDOM % digits + 1))"
  else
    printf 'The argument should be a positive integer.\n'
    exit 1
  fi
}

if [[ "$*" == *" -h"* ]] || [[ "$*" == *" --help"* ]]; then
  show_help
  exit 0
fi

case $1 in
-h)
  show_help
  exit 0
  ;;
"")
  randomize 9999
  ;;
*)
  randomize "${1}"
  ;;
esac

exit $?
